name: Deploy to EC2

# Trigger the workflow on push to the dev/env branch
on:
  push:
    branches:
      - dev/env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          PORT: ${{ secrets.PORT }}
        run: |
          # Define variables
          HOST=${{ secrets.EC2_HOST }}
          USER=${{ secrets.EC2_USER }}
          APP_DIR=/home/${USER}/dev_workspace  # Change this to your app directory
          REPO_URL=https://github.com/Reel-Hive/Reel-Hive.git  # Replace with your repo URL

          # Copy the pipeline script to the remote EC2 instance
          scp -o StrictHostKeyChecking=no pipeline.sh $USER@$HOST:$APP_DIR/pipeline.sh

          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            echo "Navigating to application directory..."
            mkdir -p $APP_DIR
            cd $APP_DIR

            echo "Setting execute permissions on the pipeline script..."
            chmod +x pipeline.sh

            echo "Running the pipeline script..."
            ./pipeline.sh \
              $HOST \
              $USER \
              $APP_DIR \
              $REPO_URL \
              "${DATABASE_URI}" \
              "${DATABASE_NAME}" \
              "${DATABASE_PASSWORD}" \
              "${PORT}"
          EOF


      - name: Deploy to prod server
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          PORT: ${{ secrets.PORT }}
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # Navigate to the application directory
            if [ ! -d "$APP_DIR/.git" ]; then
              echo "Cloning repository..."
              git clone $REPO_URL $APP_DIR
            else
              echo "Repository exists. Pulling latest changes..."
              cd $APP_DIR
              git checkout dev/env
              git pull origin dev/env
            fi



            # Navigate to the application directory
            cd $APP_DIR
            rm .env

            # Update or create the .env file with environment variables
            echo "Updating environment variables..."
            DATABASE_URI=${DATABASE_URI}
            DATABASE_NAME=${DATABASE_NAME}
            DATABASE_PASSWORD=${DATABASE_PASSWORD}
            PORT=${PORT}
            echo "DATABASE_URI=$DATABASE_URI" >> .env
            echo "DATABASE_NAME=$DATABASE_NAME" >> .env
            echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
            echo "PORT=$PORT" >> .env

            # Install dependencies (example for Node.js)
            echo "Installing dependencies..."
            npm install

            # Start the application (example using PM2)
            pm2 start server.js

            # Restart the application (example using PM2)
            echo "Restarting application..."
            pm2 restart all

            echo "Deployment completed successfully."