name: Deploy to EC2

# Trigger the workflow on push to the dev/env branch
on:
  push:
    branches:
      - dev/env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        env:
          # Pass all environment variables to the run step
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          PORT: ${{ secrets.PORT }}
          # Add more variables as needed
          run: |
          # Define variables
          HOST=${{ secrets.EC2_HOST }}
          USER=${{ secrets.EC2_USER }}
          APP_DIR=/home/${USER}/dev_workspace  # Change this to your app directory
          REPO_URL=https://github.com/Reel-Hive/Reel-Hive.git  # Replace with your repo URL

          # Save the SSH key to a file
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

          # Connect to the EC2 instance and execute commands
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << EOF
            echo "Connected to EC2"
            echo "OS Information:"
            cat /etc/os-release

            echo "Current Directory:"
            pwd

            echo "Node.js Version:"
            node -v

            echo "NPM Version:"
            npm -v

            echo "PM2 Version:"
            pm2 -v
          EOF

          # Clean up
          rm -f key.pem
